 
/**
 * Largely based on https://github.com/JM4ier/parsley/blob/main/src/producer.rs
 */

import { Chomsky } from './chomsky';
import { Terminal } from './grammar';

export class Producer {
  // words[i][j] contains a word of length i generated by rule j
  private words: Terminal[][][] = [];

  private currentWords: Set<string> = new Set<string>();

  private longestWord: number | null = null;

   
  constructor(
    private chomsky: Chomsky,
    private longestLiteral: number
  ) {}

  public static fromChomsky(chomsky: Chomsky): Producer {
    const max = Math.max(
      ...Array.from(
        chomsky.rules
          .flatMap((rule) => rule)
          .filter((def) => typeof def === 'string')
          .map((def) => def.length)
      )
    );

    const prod = new Producer(chomsky, max);
    prod.initLength(0);

    if (chomsky.nullable) {
      prod.words[0][chomsky.start].push('');
      prod.currentWords.add('');
      prod.longestWord = 0;
    }

    return prod;
  }

  public currentLength(): number {
    return this.words.length - 1;
  }

  public allWords(): Set<string> {
    return this.currentWords;
  }

  public findNext() {
    const targetLength = this.words.length;
    this.initLength(targetLength);

    this.chomsky.rules.forEach((rule, r) => {
      const newWords: Set<string> = new Set<string>();

      // add terminals ot found words, if they have the correct length
      for (const def of rule) {
        if (typeof def === 'string' && def.length === targetLength) {
          newWords.add(def);
        }
      }

      // add combination of two nonterminals to the list of words, if the two parts together are the correct length
      for (let l1 = 1; l1 < targetLength; l1++) {
        const l2 = targetLength - l1;
        for (const def of rule) {
          if (Array.isArray(def)) {
            for (const a of this.words[l1][def[0]]) {
              for (const b of this.words[l2][def[1]]) {
                newWords.add(a + b);
              }
            }
          }
        }
      }

      const values = Array.from(newWords.values());
      values.sort();

      this.words[targetLength][r] = values;
    });

    for (const word of this.words[targetLength][this.chomsky.start]) {
      this.currentWords.add(word);
      this.longestWord = targetLength;
    }
  }

  public isDone(): boolean {
    return (
      this.words.length >
      2 * Math.max(this.longestWord ?? 0, this.longestLiteral) +
        this.longestLiteral +
        1
    );
  }

  private initLength(i: number): void {
    if (this.words.length !== i) {
      throw new Error(`Expected to be of length ${i}`);
    }

    const currentLength: Terminal[][] = new Array(this.chomsky.rules.length);
    for (let j = 0; j < this.chomsky.rules.length; j++) {
      currentLength[j] = [];
    }

    this.words.push(currentLength);
  }
}
